### ISSUE TITLE
Simple Query String / Aggregations [Feature]

### ISSUE THREAD

**Issue by Mattchewone** [feathersjs/feathers-elasticsearch#22]
Just wondering what is on the roadmap for this adapter? 

I would be quite interested in seeing these above if possible. 

Any thoughts on this?

**Comment by daffl** [comment]
So far @jciolek has been doing a great job maintaining this adapter so I'll leave any roadmap decisions (and pull request reviews) to him if he has any thoughts on this.

**Comment by Mattchewone** [comment]
@daffl Thanks, I have created a PR for the `simple_query_string` query, hopefully he can have a look and decide whether it is needed to be added or not.

**Comment by daffl** [comment]
Closed via #24, thanks @Mattchewone!

**Comment by jciolek** [comment]
Hey @Mattchewone, thanks for your interest in the adapter and your contribution.

In terms of the roadmap, there a few things right now.

- I want the adapter to utilise the whole potential of ES queries. There are loads of parameters that can be set on each query, however some of them can have massive impact on performance and have to be used with caution. We would not like to give that much control to the end user by default. Instead, I would like to make the queries configurable within the service.
- I want to add aggregations, which are one of the most useful features of ES, right next to full text search. I haven't given much thought to it yet, although I am preparing a use cases for it on https://hacker-search.net, and when they are ready I believe I will know the requirements.
- I want to add `slim` mode to the adapter, so that no extra queries are fired on update, delete, etc.
- Tightly linked to the previous point, I want to utilise features added to 5.x (for example ES can return the modified document on update()).

I hope that answers your question. I would love to hear your thoughts and suggestions on the matter. Is there any functionality you are missing from the adapter?

Cheers,
Jacek
